name = "RandomProjectionTrees"
uuid = "b9212602-23e4-11e9-14f8-8345854825a4"
authors = ["Dillon Daudert <dillongdaudert@gmail.com>"]
version = "0.0.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
